[package]
name = "wotoha-analysis-lab"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
symphonia.workspace = true
wotoha-core = { path = "../wotoha-core" }
wotoha-runtime = { path = "../wotoha-runtime" }
