[package]
name = "wotoha-runtime"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
aes = "0.8.4"
async-trait.workspace = true
async-stream = "0.3.6"
beat-this.workspace = true
bytes = "1.10.1"
cipher = "0.4.4"
cbc = "0.1.2"
dashmap.workspace = true
ebur128 = "=0.1.10"
futures.workspace = true
hls_m3u8 = "0.4.1"
patricia_tree = "0.8.0"
pin-project.workspace = true
reqwest.workspace = true
rten = "0.24.0"
rten-tensor = "0.24.0"
serde.workspace = true
serde_json.workspace = true
serenity.workspace = true
sha2.workspace = true
songbird.workspace = true
symphonia.workspace = true
thiserror.workspace = true
timestretch.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true
wotoha-contracts = { path = "../wotoha-contracts" }
wotoha-control = { path = "../wotoha-control" }
wotoha-core = { path = "../wotoha-core" }
