[package]
name = "wotoha-youtube-js-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
boa_engine.workspace = true
oxc.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2.177"

[dev-dependencies]
reqwest.workspace = true
tokio.workspace = true
