[package]
name = "wotoha-app"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
ebur128 = "=0.1.10"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serenity.workspace = true
sha2.workspace = true
songbird.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
wotoha-contracts = { path = "../wotoha-contracts" }
wotoha-control = { path = "../wotoha-control" }
wotoha-core = { path = "../wotoha-core" }
wotoha-media = { path = "../wotoha-media" }
wotoha-runtime = { path = "../wotoha-runtime" }
wotoha-voice = { path = "../wotoha-voice" }
